config/routes.rb
Rails.application.routes.draw do

  

  # mount Ckeditor::Engine => '/ckeditor'
  get 'transaction/index'
  get 'setup/index'

  get 'report/index'

  get 'report/connected_calls'
  post 'report/connected_calls'

  get 'report/progress_bar'
  post 'report/progress_bar'

  get 'windows/google_lead_details'
  post 'windows/google_lead_details'

  get 'windows/daily_calling_report'
  post 'windows/daily_calling_report'

  get 'windows/site_visit_form'
  post 'windows/site_visit_form'
  post 'windows/site_visit_form_submit'
  post 'windows/walk_in_site_visit_form_submit'


  get 'report/monthly_target_index'
  get 'report/monthly_target_new'
  post'report/monthly_target_create'
  get 'report/monthly_target_edit'
  post 'report/monthly_target_update'

  get 'windows/all_live_leads_index'
  post 'windows/all_live_leads_index'
  get  'windows/whatsapp_responsiveness_report'
  post 'windows/whatsapp_responsiveness_report'

  get 'demand/booking_form'
  post 'demand/booking_form'
  get 'demand/booking_preview'
  post 'demand/booking_preview'
  get 'demand/booking_form_download_and_mail'
  post 'demand/booking_form_download_and_mail'

  get 'demand/oriental'
  post 'demand/oriental'

  post 'demand/booking_form_submit'
  get 'demand/Allotment_letter_preview'
  post 'demand/Allotment_letter_preview'
  get 'demand/allotment_letter_download_mail'
  post 'demand/allotment_letter_download_mail'

  get 'demand/send_welcome_letter'
  post 'demand/send_welcome_letter'

  get 'windows/customer_report'
  post 'windows/customer_report'

  get 'source_categories/source_tag_with_facebook_index'
  post 'source_categories/source_tag_with_facebook_index'
  get 'source_categories/source_tag_with_facebook_new'
  post 'source_categories/source_tag_with_facebook_create'
  get 'source_categories/source_tag_with_facebook_edit'
  patch 'source_categories/source_tag_with_facebook_update'
  get 'source_categories/source_tag_with_facebook_destroy'

  post 'marketing_automation/referred_lead_create'
  get 'marketing_automation/referred_lead_form'
  get 'marketing_automation/wish_to_customer_index'
  post 'marketing_automation/wish_to_customer_index'
  get 'marketing_automation/wish_to_customer_upload_form'
  post 'marketing_automation/wish_to_customer_upload'
  get 'marketing_automation/wish_to_customer_destroy'
  post 'marketing_automation/wish_to_customer_destroy'
  get 'marketing_automation/wish_to_customer_submit'
  post 'marketing_automation/wish_to_customer_submit'
  get 'marketing_automation/wish_to_customer_clear'
  post 'marketing_automation/wish_to_customer_clear'
  get 'marketing_automation/wish_to_customer_edit'
  patch 'marketing_automation/wish_to_customer_update'

  get 'marketing_automation/referred_leads_index'
  post 'marketing_automation/referred_leads_index'

  get 'marketing_automation/referral_scheme_opt'
  post 'marketing_automation/referral_scheme_opt'

  get 'setup/area_index'
  post 'setup/area_index'
  get 'setup/area_new'
  post 'setup/area_create'
  get 'setup/area_edit'
  post 'setup/area_update'
  get 'setup/area_destroy'

  get 'setup/city_index'
  post 'setup/city_index'
  get 'setup/city_new'
  post 'setup/city_create'
  get 'setup/city_edit'
  post 'setup/city_update'
  get 'setup/city_destroy'



  # get 'preferred_locations/preferred_location_tag_index'
  # post 'preferred_locations/preferred_location_tag_index'
  # get 'preferred_locations/preferred_location_tag_new'
  # post 'preferred_locations/preferred_location_tag_create'
  # get 'preferred_locations/preferred_location_tag_edit'
  # post 'preferred_locations/preferred_location_tag_update'
  # get 'preferred_locations/preferred_location_tag_destroy'

  get 'other_project/other_project_index'
  post 'other_project/other_project_index'
  get 'other_project/other_project_new'
  post 'other_project/other_project_create'
  get 'other_project/other_project_edit'
  patch 'other_project/other_project_update'
  get 'other_project/other_project_destroy'

  get 'access_point/access_point_index'
  post 'access_point/access_point_index'
  get 'access_point/access_point_new'
  post 'access_point/access_point_create'
  get 'access_point/access_point_edit'
  patch 'access_point/access_point_update'
  get 'access_point/access_point_destroy'
  get 'access_point/access_point_with_personnel'
  post 'access_point/access_point_with_personnel'
  get 'access_point/personnel_tagging_with_access_point'
  post 'access_point/personnel_tagging_with_access_point'
  post 'access_point/access_point_submit'

  get 'windows/fresh_lead_submit'
  post 'windows/fresh_lead_submit'


  get 'adhoc_charge/adhoc_charge_index'
  post 'adhoc_charge/adhoc_charge_index'
  get 'adhoc_charge/adhoc_charge_new'
  post 'adhoc_charge/adhoc_charge_create'
  get 'adhoc_charge/adhoc_charge_edit'
  patch 'adhoc_charge/adhoc_charge_update'
  get 'adhoc_charge/adhoc_charge_destroy'

  get 'credit_note_head/credit_note_head_index'
  post 'credit_note_head/credit_note_head_index'
  get 'credit_note_head/credit_note_head_new'
  post 'credit_note_head/credit_note_head_create'
  get 'credit_note_head/credit_note_head_edit'
  patch 'credit_note_head/credit_note_head_update'
  get 'credit_note_head/credit_note_head_destroy'


  get 'flats/opening_balance_index'
  post 'flats/opening_balance_index'
  get 'flats/opening_balance_edit'
  post 'flats/opening_balance_update'
  get 'marketing_automation/email_template_index'
  post 'marketing_automation/email_template_index'
  get 'marketing_automation/email_template_new'
  post 'marketing_automation/email_template_create'
  get 'marketing_automation/email_template_edit'
  patch 'marketing_automation/email_template_update'
  post 'marketing_automation/email_template_update'
  get 'marketing_automation/email_template_destroy'
  get 'marketing_automation/testing_email_template_send'
  post 'marketing_automation/testing_email_template_send'

  get 'marketing_automation/email_template_preview_index'
  post 'marketing_automation/email_template_preview_index'

  get 'marketing_automation/email_image_index'
  post 'marketing_automation/email_image_index'

  get 'marketing_automation/email_image_upload_form'
  post 'marketing_automation/email_image_upload_form'

  get 'marketing_automation/email_image_upload'
  post 'marketing_automation/email_image_upload'

  get 'marketing_automation/email_attachment_upload_form'
  post 'marketing_automation/email_attachment_upload_form'

  get 'marketing_automation/email_attachment_upload'
  post 'marketing_automation/email_attachment_upload'

  get 'marketing_automation/whatsapp_image_upload_form'
  post 'marketing_automation/whatsapp_image_upload_form'

  get 'marketing_automation/whatsapp_image_upload'
  post 'marketing_automation/whatsapp_image_upload'

  get 'marketing_automation/bulk_recipient_index'
  post 'marketing_automation/bulk_recipient_index'
  get 'marketing_automation/bulk_recipient_upload_form'
  post 'marketing_automation/bulk_recipient_upload'
  get 'marketing_automation/bulk_recipient_destroy'
  post 'marketing_automation/bulk_recipient_destroy'
  get 'marketing_automation/bulk_recipient_submit'
  post 'marketing_automation/bulk_recipient_submit'
  get 'marketing_automation/bulk_recipient_clear'
  post 'marketing_automation/bulk_recipient_clear'
  get 'marketing_automation/whatsapp_template_index'
  post 'marketing_automation/whatsapp_template_index'
  get 'marketing_automation/whatsapp_template_new'
  post 'marketing_automation/whatsapp_template_create'
  get 'marketing_automation/whatsapp_template_edit'
  patch 'marketing_automation/whatsapp_template_update'
  post 'marketing_automation/whatsapp_template_update'
  get 'marketing_automation/whatsapp_template_destroy'

  get 'marketing_automation/whatsapp_image_index'
  post 'marketing_automation/whatsapp_image_index'

  get 'marketing_automation/whatsapp_image_upload_form'
  post 'marketing_automation/whatsapp_image_upload_form'

  get 'marketing_automation/whatsapp_image_upload'
  post 'marketing_automation/whatsapp_image_upload'




  get 'marketing_automation/whatsapp_template_preview_index'
  post 'marketing_automation/whatsapp_template_preview_index'

  get 'marketing_automation/testing_whatsapp_template_send'
  post 'marketing_automation/testing_whatsapp_template_send'

  get 'marketing_automation/sms_template_index'
  post 'marketing_automation/sms_template_index'
  get 'marketing_automation/sms_template_new'
  post 'marketing_automation/sms_template_create'
  get 'marketing_automation/sms_template_edit'
  patch 'marketing_automation/sms_template_update'
  post 'marketing_automation/sms_template_update'
  get 'marketing_automation/sms_template_destroy'
  get 'marketing_automation/sms_template_preview_index'
  post 'marketing_automation/testing_sms_template_send'


  get 'windows/template_send'

  get 'demand/e_signature'
  post 'demand/e_signature'

  get 'demand_report/future_demand_index'
  post 'demand_report/future_demand_index'
  get 'demand_report/demand_accrued_interest'
  post 'demand_report/demand_accrued_interest'

  get 'demand_report/area_unit_wise_demand_index'
  post 'demand_report/area_unit_wise_demand_index'

  get 'demand_report/ledger_entry_header_index'
  post 'demand_report/ledger_entry_header_index'

  get 'demand_report/demand_notice_index'
  post 'demand_report/demand_notice_index'

  get 'demand_report/demand_notice_download_mail'
  post 'demand_report/demand_notice_download_mail'

  get 'demand_report/ignore_demand_index'
  post 'demand_report/ignore_demand_index'

  get 'demand_report/restore_demands'
  post 'demand_report/restore_demands'

  get 'demand_report/multi_demand_destroy'
  post 'demand_report/multi_demand_destroy'

  get 'demand/booking_submit_for_action'
  post 'demand/booking_submit_for_action'

  get 'demand/unconfirmed_booking'
  post 'demand/unconfirmed_booking'

  get 'demand/mortgage_noc_preview'
  post 'demand/mortgage_noc_preview'
  get 'demand/mortgage_noc_send'
  post 'demand/mortgage_noc_send'

app/models/credit_note_head.rb
class CreditNoteHead < ApplicationRecord
	belongs_to :organisation
end

app/controllers/credit_note_head_controller.rb
class CreditNoteHeadController < ApplicationController
	def credit_note_head_index
		@credit_note_heads=CreditNoteHead.includes(:organisation).where(organisation_id: current_personnel.organisation_id)
	end

	def credit_note_head_new
		@credit_note_head=CreditNoteHead.new
		@credit_note_head_action = 'credit_note_head_create'
	end

	def credit_note_head_create
		credit_note_head=CreditNoteHead.new(credit_note_head_params)
		credit_note_head.organisation_id = current_personnel.organisation_id
		credit_note_head.save

		flash[:success]='Credit Note Head Generated successfully.'
		redirect_to credit_note_head_credit_note_head_index_url
	end

	def credit_note_head_edit
		@credit_note_head=CreditNoteHead.find(params[:format])
		@credit_note_head_action = 'credit_note_head_update'
	end

	def credit_note_head_update
		@credit_note_head=CreditNoteHead.find(params[:credit_note_head_id])
		@credit_note_head.update(credit_note_head_params)

		flash[:success]='Credit Note Head Updated successfully.'
		redirect_to credit_note_head_credit_note_head_index_url
	end

	def credit_note_head_destroy
		@credit_note_head=CreditNoteHead.find(params[:format])
		@credit_note_head.destroy

		flash[:success]='Credit Note Head Destroyed successfully.'
		redirect_to credit_note_head_credit_note_head_index_url
	end

	def credit_note_register
		@credit_note_entries=CreditNoteEntry.includes(:booking, :credit_note_head).where(:credit_note_heads => {organisation_id: current_personnel.organisation_id})
	end
	

	private
		def credit_note_head_params
			params.require(:credit_note_head).permit(:description)
		end
end

app/helpers/credit_note_head_helper.rb
module CreditNoteHeadHelper
end

app/views/credit_note_head/_credit_note_head_form.html.erb
<div class="col-lg-5 col-lg-offset-3">
	<div class="well bs-component">
		<center><legend>Credit Note Head</legend></center>
		<%= form_for @credit_note_head, url: {action: @credit_note_head_action} do |f| %>
  		  <% if @credit_note_head.errors.any? %>
		    <div id="error_explanation">
		      <h2><%= pluralize(@credit_note_head.errors.count, "error") %> prohibited this credit_note_head from being saved:</h2>

		      <ul>
		      <% @credit_note_head.errors.full_messages.each do |message| %>
		        <li><%= message %></li>
		      <% end %>
		      </ul>
		    </div>
		  <% end %>
		  <div class="row">
		  	<div class="col-lg-2">
		    	<%= f.label :Description, :class => "control-label" %>
		    </div>
		    <div class="col-lg-10">
		    	<%= f.text_field :description, :class => "form-control" %>
		  	</div>
	      </div><br>
	  	  <div class="row">
	      	<div class="col-lg-8 col-lg-offset-2">
	    		<%= f.submit :class => 'btn btn-primary btn-block'%>
	  		</div>
	      </div>
	      <%= hidden_field_tag :credit_note_head_id, @credit_note_head.id%>
	    <% end %>
  	</div>
</div>

app/views/credit_note_head/credit_note_head_edit.html.erb
<%@header = 'Credit Notes Edit'%>
<%= render 'credit_note_head_form'%>

app/views/credit_note_head/credit_note_head_index.html.erb
<%@header = 'Credit Notes'%>
<h1>Credit Note Heads</h1>

<table id="customers">
  <thead>
    <tr>
      <th>Description</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @credit_note_heads.each do |credit_note_head| %>
      <tr>
        <td><%= credit_note_head.description %></td>
        <td><%= link_to 'Edit', credit_note_head_credit_note_head_edit_path(credit_note_head), :class => "edit_btn", :style => "text-decoration: none;"%></td>
        <td><%= link_to 'Destroy', credit_note_head_credit_note_head_destroy_path(credit_note_head), :class => "dlt_btn", :style => "text-decoration: none;", data: { confirm: 'Are you sure ?'}%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Credit Note Head', credit_note_head_credit_note_head_new_path, :class => 'btn btn-primary' %>

app/views/credit_note_head/credit_note_head_new.html.erb
<%= render 'credit_note_head_form'%>

app/views/credit_note_head/credit_note_register.html.erb
<%@header = 'Demand Credit Note Register'%>
<h1>Credit Notes</h1>

<table id="customers">
  <thead>
    <tr>
      <th>Customer</th>
      <th>Credit Note Head</th>
      <th>Amount</th>
      <th>Date</th>
      <th>Remarks</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @credit_note_entries.each do |credit_note_entry| %>
      <tr>
        <td><%= credit_note_entry.booking.cost_sheet.lead_id %></td>
        <td><%= credit_note_entry.credit_note_head.description%></td>
        <td><%= credit_note_entry.amount%></td>
        <td><%= credit_note_entry.date.to_date.strftime('%d/%m/%Y')%></td>
        <td><%= credit_note_entry.try(:remarks)%></td>
        <td><%= link_to 'Edit', demand_credit_note_edit_path(credit_note_entry), :class => "edit_btn", :style => "text-decoration: none;"%></td>
        <td><%= link_to 'Destroy', demand_credit_note_destroy_path(credit_note_entry), :class => "dlt_btn", :style => "text-decoration: none;", data: { confirm: 'Are you sure ?'}%></td>
        <td><%= link_to 'Preview', demand_credit_note_preview_index_path(credit_note_entry), :class => "btn btn-primary"%></td>
      </tr>
    <% end %>
  </tbody>
</table>